modLoader="javafml" 
loaderVersion="[40,)"
license="All rights reserved"
[[mods]] 
modId="ascendancytools" 
version="${file.jarVersion}" 
displayName="Ascendancy Tools" 
logoFile="logo.png" 
credits="Wolforce" 
authors="Wolforce" 
description='''
Tools that have inverse durability
'''
[[dependencies.ascendancytools]] 
    modId="forge" 
    mandatory=true 
    versionRange="[40,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.ascendancytools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
